// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWepApp.BlazorApp.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

#nullable disable

namespace TestWepApp.BlazorApp.Migrations.PizzaPlaceDb
{
    [DbContext(typeof(PizzaPlaceDbContext))]
    partial class PizzaPlaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestWepApp.BlazorApp.Data.PizzaPlace.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Spiciness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}



//PM > dotnet - ef migrations add CreatingPizzaPlaceDb --project TestWepApp.BlazorApp 
//Build started...
//Build succeeded.
//More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands.
//PM> dotnet-ef migrations add CreatingPizzaPlaceDb --project TestWepApp.BlazorApp 
//Build started...
//Build succeeded.
//More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands.
//PM> dotnet-ef migrations add CreatingPizzaPlaceDb --project TestWepApp.BlazorApp 
//Build started...
//Build succeeded.
//More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands.
//PM> 
//PM> 
//PM> dotnet-ef migrations add CreatingPizzaPlaceDB --context PizzaPlaceContext
//No project was found. Change the current working directory or use the --project option.
//PM> dotnet-ef migrations add CreatingPizzaPlaceDb --project TestWepApp.BlazorApp --context PizzaPlaceDbContext
//Build started...
//Build succeeded.
//Done. To undo this action, use 'ef migrations remove'
//PM> 



//dotnet - ef database update --project TestWepApp.BlazorApp --context PizzaPlaceDbContext


